rundeck_db:
    image: postgres:9.4.5
    environment:
        POSTGRES_USER: rundeck
        POSTGRES_PASSWORD: rundeck
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    ports:
        - "192.168.59.103:5432:5432"

rundeck:
    build: .
    ports:
        - "192.168.59.103:4440:4440"
    links:
        - rundeck_db:db
    volumes:
        - ./rundeck-configs/var/lib/rundeck.ssh/:/var/lib/rundeck.ssh
        - ./rundeck-configs/var/log/rundeck:/var/log/rundeck
